<?php
define('FILENAME_YOUR_MODULE_NAME', 'YOUR_MODULE_NAME.php');  
define('MODULE_FOLDER_YOUR_MODULE_NAME', DIR_WS_MODULES . 'YOUR_MODULE_NAME/');


define('BOX_TOOLS_YOUR_MODULE_NAME', 'YOUR_MODULE_NAME');
define('BOX_CONFIGURATION_YOUR_MODULE_NAME', 'YOUR_MODULE_NAME');
